services:
  dsmoo:
    image: ghcr.io/grafdimenzio/dsmoo:dev
    container_name: dsmoo
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - "1027:1027"
    volumes:
      - dsmoo:/dsmoo

volumes:
  dsmoo:

environment:
  - DOTNET_GCServer=1
  - DOTNET_ThreadPool_MinThreads=50

logging:
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"
